In [1]:
from scipy.io.wavfile import write
import numpy as np

samplerate = 16000

In [2]:
data_input = np.genfromtxt("recording_a.txt", delimiter=',')  
print(data_input)

[[ 0.00000e+00 -1.66400e+03 -1.92000e+03]
 [ 0.00000e+00 -1.66400e+03 -1.92000e+03]
 [ 1.00000e+00 -1.79200e+03 -2.04800e+03]
 ...
 [ 1.06704e+05  7.68000e+02  1.02400e+03]
 [ 1.06705e+05  8.96000e+02  1.02400e+03]
 [ 1.06705e+05  8.96000e+02  1.02400e+03]]


In [3]:
data_input = data_input.T
print(data_input)

[[ 0.00000e+00  0.00000e+00  1.00000e+00 ...  1.06704e+05  1.06705e+05
   1.06705e+05]
 [-1.66400e+03 -1.66400e+03 -1.79200e+03 ...  7.68000e+02  8.96000e+02
   8.96000e+02]
 [-1.92000e+03 -1.92000e+03 -2.04800e+03 ...  1.02400e+03  1.02400e+03
   1.02400e+03]]


In [4]:
data_serial_number = data_input[0]
print(data_serial_number)

[0.00000e+00 0.00000e+00 1.00000e+00 ... 1.06704e+05 1.06705e+05
 1.06705e+05]


In [5]:
left_channel = data_input[1]
print(left_channel)

[-1664. -1664. -1792. ...   768.   896.   896.]


In [6]:
right_channel = data_input[2]
print(right_channel)

[-1920. -1920. -2048. ...  1024.  1024.  1024.]


In [7]:
dual_channel = left_channel + right_channel
dual_channel = dual_channel / 2
print(dual_channel)

[-1792. -1792. -1920. ...   896.   960.   960.]


In [8]:
write("Recording_0724.wav", samplerate, dual_channel.astype(np.int16))